### ISSUE TITLE
Reproduce Neural Network Results

### ISSUE THREAD

**Issue by AmirooR** [dirichletcal/experiments_neurips#1]
Hi,
Thanks for providing the code of your paper. I have looked into your code, but couldn't find a way to reproduce your NeurIPS paper results for deep network calibration. I even reimplemented your code. However, the results are different from what you've reported. Could you please provide a way to produce the same results with your code?

Best,

**Comment by perellonieto** [comment]
Hi AmirooR,

we forgot to indicate that the DNN experiments are in the separated repository [experiments_dnn](https://github.com/dirichletcal/experiments_dnn). We have specified this information in the commit aac266c

I hope this solves this issue. Please let us know if you have any problem running the code in the other repository.

Best,
